### ISSUE TITLE
Note about not being associated with jw.org

### ISSUE THREAD

**Issue by JoelMon** [jw-devs/jw-devs.github.com#7]
I think there should be a note stating that this group has no association with JW.org especially since the logo looks so close to the offical JW.ORG logo. Without the note people might think this group is official or something which would not be a good idea.

I would also suggest getting a logo that doesn't look like an official JW.ORG logo...

**Comment by mjacobus** [comment]
+1

**Comment by ream88** [comment]
Notice is ok, however I don't agree with the logo change

**Comment by ream88** [comment]
But my opinion may change 😉 suggestions?

**Comment by ream88** [comment]
![new](https://cloud.githubusercontent.com/assets/14321/14922324/41224dd6-0e37-11e6-98af-e5334f4aad9c.png)

**Comment by andresavic** [comment]
http://tmsearch.uspto.gov/bin/showfield?f=doc&state=4804:z51gx5.2.1

Legally, I think there is no problem. Danger of confusion, maybe...

The problem is that a professional looking logo, always looks "officially" :D

**Comment by ream88** [comment]
```
     _________
     \__    _/|\     /|
        )  (  | )   ( |
        |  |  | | _ | |
        |  |  | |( )| |
        |  |  | || || |
     |\_)  )  | () () |
     (____/   (_______)
         _
       _| |___ _ _ ___
     _| . | -_| | |_ -|
    |_|___|___|\_/|___|
```

Haha, don't judge me ;)

**Comment by mjacobus** [comment]
If it is not illegal then a notice might suffice

**Comment by karlingen** [comment]
👍
